import './globals.css'
import { Inter } from 'next/font/google'
import { Providers } from "./providers";
const inter = Inter({ subsets: ['latin'] })
import NavbarAdmin from '@/components/shared/nav/NavbarAdmin'
import NavbarHome from '@/components/shared/nav/NavbarHome'
import Footer from '@/components/shared/footer/Footer'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
          <body className={inter.className}>
          <Providers>
            <NavbarHome/>
            {/* <NavbarAdmin  
              logoText={"Horizon UI Dashboard PRO"}
              brandText={'test'}
              secondary={false}
              message={'test'}
            /> */}
            {children}
            
          </Providers>
          </body>
    </html>
  )
}

